### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by bartolomeu** [Availity/availity-reactstrap-validation#189] opened 2020-04-28 22:08 UTC
Consolo is warning this message

>Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
>
>* Move code with side effects to componentDidMount, and set initial state in the constructor.
>* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
>
>Please update the following components: AvForm, AvInput, AvRadioGroup

I'm using 
React -  16.13.1
availity-reactstrap-validation - ^2.6.1

**Comment by bartolomeu** [comment] 2020-04-28 22:29
I'm creating a minimum case test

**Comment by GoPro16** [comment] 2020-04-28 22:33
duplicate of #155

**Closed by GoPro16** 2020-04-28 22:33 UTC
