### ISSUE TITLE
Warning for AvForm componentWillMount?

### ISSUE THREAD

**Issue by LMarlette** [Availity/availity-reactstrap-validation#171] opened 2019-12-06 03:46 UTC
Im getting this warning even though I have 2.6.1 installed.

> [Warning] Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details. (0.chunk.js, line 63054)
> 
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: AvForm

**Comment by jonbnewman** [comment] 2020-02-08 20:53
I am also seeing this on `AvInput` as well...running version 2.6.1

**Comment by GoPro16** [comment] 2020-02-10 14:10
Duplicate of #155

**Closed by GoPro16** 2020-02-10 14:10 UTC
