### ISSUE TITLE
How do I Validate Input Type Select

### ISSUE THREAD

**Issue by kevalmalde** [Availity/availity-reactstrap-validation#71] opened 2018-03-27 14:44 UTC
Suppose I have a below select element: 
`<AvField
                      type="select"
                      id="SalaryType"
                      name="SalaryType"
                      helpMessage=""
                      required
                    >
                      <option>Select Frequency of Salary</option>
                      <option value="1">Monthly</option>
                      <option value="2">Bi-Weekly</option>
                      <option value="3">Weekly</option>
                      <option value="4">Fortnightly</option>
                    </AvField>`

Is there a option to show error when selected option is 'Select Frequency of Salary'?

**Comment by TheSharpieOne** [comment] 2018-03-27 15:29
If no `value` is set on an `<option>` it will default to the text with in the `<option>` (this is per the HTML spec and is handled by the browser). So, the first option ends up having the value of `Select Frequency of Salary`, which is not empty so it passes the `required` validation.
If you add `value=""` to the option, it should work as you intended.
Demo: https://stackblitz.com/edit/reactstrap-validation-v2-zk6fkc?file=Example.js

Also, since the default value is will be `""` (after the change mentioned above), it will not show the error initially. If the user changes the value and then changes it back, it should show the error. Additional, it the user doesn't change the value and tries to submit the form, it should show the error.

**Comment by kevalmalde** [comment] 2018-03-28 05:10
Thanks @TheSharpieOne, This Works.
I have one more query, right now it shows error message `This field is invalid`, Is there a way to provide custom error message for AvField

**Comment by TheSharpieOne** [comment] 2018-03-28 12:55
Take a  look at #19

**Comment by TheSharpieOne** [comment] 2018-06-05 21:45
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2018-06-05 21:45 UTC

**Comment by alisherabuhabiba2202** [comment] 2020-10-14 12:39
> If no `value` is set on an `<option>` it will default to the text with in the `<option>` (this is per the HTML spec and is handled by the browser). So, the first option ends up having the value of `Select Frequency of Salary`, which is not empty so it passes the `required` validation.
> If you add `value=""` to the option, it should work as you intended.
> Demo: https://stackblitz.com/edit/reactstrap-validation-v2-zk6fkc?file=Example.js
> 
> Also, since the default value is will be `""` (after the change mentioned above), it will not show the error initially. If the user changes the value and then changes it back, it should show the error. Additional, it the user doesn't change the value and tries to submit the form, it should show the error.

Thank you
